issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:doximity/.*:ref:refs/heads/.*
claim_pattern:
  job_workflow_ref: doximity/dox-gh-shared-workflows/\.github/workflows/renovate\.yml@.*

permissions:
  contents: write
  pull_requests: write
  issues: write
  actions: write
